version: "3"

services:
  caddy:
    image: caddy:latest

    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - $PWD/data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  site:
    build:
      context: site
      dockerfile: Dockerfile

    depends_on:
      - caddy

    ports:
      - "8000:80"

  grafana:
    image: 'grafana/grafana-oss'
    restart: always

    depends_on:
      - caddy

    ports:
      - "3000:3000"

  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab.xithrius.cloud'

    depends_on:
    - caddy

    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.xithrius.cloud:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224

    ports:
      - "8929:8929"
      - "2224:22"

    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'

    shm_size: '256m'

  prometheus:
    image: 'prom/prometheus'
    user: root
    restart: always

    depends_on:
      - caddy
      - grafana

    ports:
      - "9090:9090"

    volumes:
      - $PWD/data/prometheus:/etc/prometheus/:rw
      - $PWD/data/prometheus/prometheus_data:/prometheus:rw
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  cloudflare:
    image: 'ghcr.io/lablabs/cloudflare_exporter'
    restart: always

    depends_on:
      - caddy
      - grafana
      - prometheus

    ports:
      - "8080:8080"

    environment:
      - FREE_TIER=true

    env_file:
      - .env

networks:
  gitlab:

volumes:
  caddy_data:
    external: true
  caddy_config:
