version: "3.3"

x-default: &default
  restart: always
  logging:
    driver: "json-file"
    options:
      max-size: "50m"

services:
  caddy:
    <<: *default

    image: caddy:latest

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  site:
    <<: *default

    build:
      context: site
      dockerfile: Dockerfile

    depends_on:
      - caddy

    ports:
      - "8001:8001"

  postgres:
    <<: *default

    image: "postgres:14-alpine"

    environment:
      POSTGRES_USER: site
      POSTGRES_PASSWORD: site
      POSTGRES_DB: site

    ports:
      - "7777:5432"

    volumes:
      - ./postgres:/var/lib/postgresql/data

  gitea:
    <<: *default

    image: "gitea/gitea:latest"

    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: postgres:5432
      GITEA__database__NAME: site
      GITEA__database__USER: site
      GITEA__database__PASSWD: site

    volumes:
      - $PWD/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    ports:
      - "3001:3001"
      - "222:22"

    depends_on:
      - postgres
      - caddy

  grafana:
    <<: *default

    image: "grafana/grafana"

    depends_on:
      - caddy

    ports:
      - "3000:3000"

    volumes:
      - grafana-storage:/var/lib/grafana

  prometheus:
    <<: *default

    build: ./prometheus

    depends_on:
      - grafana

    ports:
      - "127.0.0.1:9090:9090"

    volumes:
      - prometheus-storage:/prometheus

  cadvisor:
    <<: *default

    image: gcr.io/cadvisor/cadvisor:v0.44.0

    ports:
      - "127.0.0.1:8080:8080"

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  node_exporter:
    <<: *default

    image: prom/node-exporter:v1.3.1

    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

    volumes:
      - '/:/host:ro,rslave'

volumes:
  caddy_data:
    external: true
  caddy_config:
  grafana-storage:
    external: true
  prometheus-storage:
